export const WILL_ID = "4929094e-c011-702f-c436-5b0fa299fcd6"
export const BRANDON_ID = "0939891e-9051-7094-a225-cb32b37186d6"
export const SEAN_ID = "396919ce-2031-70c2-59a5-08ebc77f3cc1"

export const BEER_PARENT_TYPES: { [key: string] : string[] } = {
    'BOCKS': ['Doppelbock', 'Eisbock', 'Bock', 'Weizenbock', 'Maibock'],
    'BROWN ALES': ['American Brown Ale', 'Altbier', 'English Brown Ale'],
    'DARK ALES': ['Dubbel', 'Winter Warmer', 'Scottish Ale'],
    'DARK LAGERS': ['Märzen',
     'Czech Dark Lager',
     'Munich Dunkel',
     'American Amber / Red Lager',
     'Vienna Lager',
     'Schwarzbier',
     'Rauchbier',
     'European Dark Lager'],
    'HYBRID / SPECIALTY BEERS': ['Fruit and Field Beer',
     'Cream Ale',
     'Happoshu',
     'Pumpkin Beer',
     'California Common / \nSteam Beer',
     'Cider',
     'Mead',
     'Herb and Spice Beer',
     'Gose',
     'Flanders Red Ale',
     'Brett Beer',
     'Smoked Beer',
     'Berliner Weisse',
     'Wild Ale',
     'Braggot',
     'Rye Beer',
     'Chile Beer'],
    'INDIA PALE ALES': ['Belgian IPA',
     'New England IPA',
     'Imperial IPA',
     'American IPA',
     'English IPA',
     'Milkshake IPA'],
    'PALE ALES': ['Irish Red Ale',
     'American Amber / Red Ale',
     'Belgian Blonde Ale',
     'Belgian Enkel',
     'American Blonde Ale',
     'Saison',
     'English Bitter',
     'Belgian Pale Ale',
     'Extra Special / Strong Bitter',
     'English Pale Ale',
     'American Pale Ale',
     'Kölsch'],
    'PALE LAGERS': ['Festbier / Wiesnbier',
     'Bohemian / Czech Pilsner',
     'German Pilsner',
     'Helles',
     'American Lager',
     'India Pale Lager',
     'Malt Liquor',
     'American Adjunct Lager',
     'European Pale Lager',
     'Kellerbier / Zwickelbier',
     'Japanese Rice Lager',
     'European / Dortmunder Export Lager',
     'Light Lager',
     'Kölsch',
     'Czech Pale Lager',
     'European Strong Lager'],
    'PORTERS': ['English Porter',
     'Imperial Porter',
     'American Porter',
     'Robust Porter',
     'Baltic Porter'],
    'STOUTS': ['Sweet / Milk Stout',
     'Russian Imperial Stout',
     'American Imperial Stout',
     'American Stout',
     'Oatmeal Stout',
     'English Stout',
     'Irish Dry Stout',
     'White / Golden Stout'],
    'STRONG ALES': ['Quadrupel',
     'Tripel',
     'Belgian Dark Strong Ale',
     'Belgian Pale Strong Ale',
     'Scotch Ale / Wee Heavy',
     'American Strong Ale',
     'Old Ale',
     'American Barleywine'],
    'WHEAT ALES': ['Witbier',
     'Hefeweizen',
     'Dunkelweizen',
     'American Pale Wheat Beer',
     'Kristallweizen',
     'Fruit and Field Beer',
     'American Dark Wheat Beer']
}

export const INVALID_BEER_NAME_MESSAGE = 'Beer name already exists in database!'